eureka:
  client:
    enabled: false

security:
  jwt:
    issuer: ${JWT_ISSUER:account-api}
    audiences:
      - account-api
    allowed-algorithms:
      - rs256

nhn:
  server-host: http://localhost:10404

clients:
  inventory:
    base-url: ${INVENTORY_BASE_URL:http://localhost:10411}

spring:
  config:
    import: optional:file:./.env[.properties]

management:
  tracing:
    export:
      zipkin:
        enabled: false
