eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    com.nhnacademy.account: INFO

management:
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}

security:
  jwt:
    issuer: ${JWT_ISSUER:account-api}
    audiences:
      - account-api
    allowed-algorithms:
      - rs256
    private-key-path: ${JWT_PRIVATE_KEY_PATH}

nhn:
  server-host: https://iunot.cloud
