eureka:
  client:
    enabled: false

security:
  jwt:
    issuer: account-api
    jwk-set-uri: http://localhost:${server.port:8080}/.well-known/jwks.json
    audiences:
      - account-api
    allowed-algorithms:
      - rs256