spring:
  application:
    name: account
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never
  tracing:
    export:
      zipkin:
        enabled: false

server:
  port: ${SERVER_PORT:10413}

security:
  jwt:
    issuer: account-api
    jwk-set-uri: http://localhost:${server.port:8080}/.well-known/jwks.json
    audiences:
      - account-api
    allowed-algorithms:
      - rs256
    private-key-path: ${JWT_PRIVATE_KEY_PATH:${java.io.tmpdir}/account/jwt-private.pem}
