= Account Service API
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:source-highlighter: highlightjs

== 인증

=== 로그인

operation::login[]

== 회원

=== 회원 가입

operation::create-account[]

=== 내 정보 조회

operation::get-current-account[]

=== 이름 변경

operation::update-account-name[]

=== 비밀번호 변경

operation::update-account-password[]

=== 회원 탈퇴

operation::withdraw-account[]

=== 이메일 사용 가능 여부 확인

operation::check-email-availability[]

=== 비밀번호 재사용 여부 확인

operation::check-password-availability[]

=== 비밀번호 초기화 토큰 발급

operation::issue-password-reset-token[]

=== 비밀번호 초기화

operation::reset-password[]

==== 유효하지 않은 토큰

operation::reset-password-invalid-token[]

== 관리자

=== 회원 목록 조회

operation::admin-list-accounts[]

==== 탈퇴 회원 개인정보 비노출

operation::admin-list-withdrawn-accounts[]

=== 회원 상태 변경

operation::admin-change-account-status[]

==== 상태 변경 사유 검증 실패

operation::admin-change-account-status-validation-error[]

==== 관리자 권한 없음

operation::admin-change-account-status-forbidden[]

=== 회원 이름 변경

operation::admin-update-account-name[]

=== 회원 비밀번호 변경

operation::admin-update-account-password[]
